shell:
  program: /bin/bash
  args:
    - --login

# Since vim isn't able to pick up Cmd itself
key_bindings:
      # Send 'prefix + p' for Cmd + j
  - { key: J, mods: Command, chars: "\x02p" }
    #Send 'prefix + n' for Cmd + k
  - { key: K, mods: Command, chars: "\x02n" }
    #Send standard tmux shortcuts for Option/Alt + h/j/k/l
  - { key: H, mods: Alt, chars: "\x02h" } # Option/Alt + h -> prefix + l (switch to left pane)
  - { key: J, mods: Alt, chars: "\x02j" } # Option/Alt + j -> prefix + j (switch to bottom pane)
  - { key: K, mods: Alt, chars: "\x02k" } # Option/Alt + k -> prefix + k (switch to top pane)
  - { key: L, mods: Alt, chars: "\x02l" } # Option/Alt + l -> prefix + h (switch to right pane)

# Configure Option key as Meta key
#window.option_as_alt: true
  #alt_send_esc: true

# Base16 Monokai 256 - alacritty color config
# Wimer Hazenberg (http://www.monokai.nl)
colors:
  # Default colors
  primary:
    background: '0x272822'
    foreground: '0xf8f8f2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x272822'
    cursor: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x272822'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x75715e'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf9f8f5'

  indexed_colors:
    - { index: 16, color: '0xfd971f' }
    - { index: 17, color: '0xcc6633' }
    - { index: 18, color: '0x383830' }
    - { index: 19, color: '0x49483e' }
    - { index: 20, color: '0xa59f85' }
    - { index: 21, color: '0xf5f4f1' }
